#!/bin/bash
# A shell script to print each number five times.
n=0
k=1
r=100
players=( 
seven.f10.g1.players.NaivePlayer seven.f10.g3.OurPlayer seven.f10.g4.G4Player seven.f10.g5.Ninja seven.f10.g6.InitialPlayer seven.f10.g7.ClassyPlayer seven.f10.g9.BiddingPlayer
)
for((h = 0; h <=7; h++))
do
		#r=$(100)
		#if [$h == 7]
		#then r=$(200)
		#fi
			
		  if [ $i -ne $j ]
          then
          java -Xmx1000M -cp bin:bin/seven/g2/log4j-1.2.15.jar seven.ui.GameEngine "seven.f10.g1.players.NaivePlayer seven.f10.g3.OurPlayer seven.f10.g4.G4Player seven.f10.g5.Ninja seven.f10.g6.InitialPlayer seven.f10.g7.ClassyPlayer seven.f10.g9.BiddingPlayer" $h 100 8player_tourney.txt
          n=$(($n+$k))
          fi
done
echo "played $n rounds"
